name: howdyfoax
favicon: null
layout_spectrum: 0.09589300327934325
typography_spectrum: 0.40697164298035204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5377066084183753
  lightness: 0.5872119292616844
  saturation: 0.12824682192876935
  rhythmicContrast: 0.39939437387511134
purpose: []
