analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.09589300327934325
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.1282468219287694
  brandStrength: 0.5377066084183753
  rhythmicContrast: 0.3993943738751113
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.5872119292616844
purpose: []
favicon: null
name: howdyfoax
typography_spectrum: 0.406971642980352
